### ISSUE TITLE
bug(indentation): grunt-indentation doesn't convert spaces to tabs, if tabs in the file beginning

### ISSUE THREAD

**Issue by Kristinita** [gespinha/grunt-indentator#1]
### 1. Summary

**If** indentation at the beginning of the file — tabs, but then — spaces:

    grunt-indentator doesn't convert spaces to tabs.

### 2. Argumentation

I need to find any method, that convert spaces to tabs inside HTML `<pre>` tags, because [**my generation tool does not do this**](https://github.com/facelessuser/pymdown-extensions/issues/276). `<pre>` tags not in beginning of the files → I can't convert spaces inside `<pre>` to tabs via grunt-indentator.

### 3. Environment

+ Windows 10 Enterprise LTSB 64-bit EN,
+ Node.js 9.11.1,
+ npm 5.8.0,
+ grunt-cli 1.2.0,
+ grunt 1.0.2,
+ grunt-indentator 0.1.4.

### 4. Configuration

my `Gruntfile.coffee`:

```coffee
module.exports = (grunt) ->

	grunt.loadNpmTasks('grunt-indentator');
	grunt.initConfig
		indentator:
			options:
				type: 'tab'
				size: 1
				debug: true
			files:
				[
					'SashaGruntIndentator.html'
				]

```

my `SashaGruntIndentator.html`:

```html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Sasha title</title>
</head>
<body>
<div class="highlight"><pre><span></span><span class="p">{</span>
    <span class="nt">&quot;name&quot;</span><span class="p">:</span> <span class="s2">&quot;SashaSuperFences&quot;</span><span class="p">,</span>
<span class="p">}</span>
</pre></div>
</body>
</html>

```

+ tabs — lines 4, 5;
+ spaces — line 9.

### 5. Steps to reproduce

	grunt indentator --verbose

### 6. Expected behavior

Convert spaces to tab in line 9.

### 7. Actual behavior

Still spaces in line 9.

```node
D:\SashaDemoRepositories\SashaGruntDebugging>grunt indentator --verbose
Initializing
Command-line options: --verbose

Reading "Gruntfile.coffee" Gruntfile…OK

Registering Gruntfile tasks.

Registering "grunt-indentator" local Npm module tasks.
Reading D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\grunt-indentator\package.json…OK
Parsing D:\SashaDemoRepositories\SashaGruntDebugging\node_modules\grunt-indentator\package.json…OK
Loading "indentator.js" tasks…OK
+ indentator
Initializing config…OK
Loading "Gruntfile.coffee" tasks…OK
>> No tasks were registered or unregistered.

Running tasks: indentator

Running "indentator" task

Running "indentator:files" (indentator) task
Verifying property indentator.files exists in config…OK
Files: SashaGruntIndentator.html -> files
Options: type="tab", size=1, debug
Reading SashaGruntIndentator.html…OK
>> SashaGruntIndentator.html
>> 1 (tab) -> 1 (tab)

Writing SashaGruntIndentator.html…OK
>> 1 file converted successfully.

Done.
```

Thanks.

**Comment by gespinha** [comment]
Hey, I'm sorry for the delay, I've just got the chance to review this issue now.

Currently, the plugin only converts **spaces to tabs** or **tabs to spaces** in a literal manner, so if you have a mix of spaces and tabs in a single file, the plugin will only look for the ones that need to be converted.

This happens because it is impossible to establish a difference between what is text related spacing and what is just an indentation on the code.

I hope this helps. Since there is no current workaround this issue, I'll mark this issue as closed.

Thanks for reporting!

**Comment by Kristinita** [comment]
**Status: :crying_cat_face: Not fixed**

Thanks.
